---
- name: Installing and Setting up SuiteCRM (inluding MySQL setup)
  ansible.builtin.import_tasks: install_packages.yaml

- name: Configure PHP Settings
  ansible.builtin.import_tasks: configure_php.yaml

- name: Install and Configure MySQL
  ansible.builtin.import_tasks: manage_mysql.yaml

- name: Install and Configure SuiteCRM
  ansible.builtin.import_tasks: install_suitecrm.yaml

- name: Configure Apache2 webserver
  ansible.builtin.import_tasks: configure_apache.yaml
