---
- name: Start and enable MySQL
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
  register: mysql_service
  failed_when: mysql_service.state != 'started'

- name: Set MySQL root password
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ suitecrm_db_root_password }}"
    state: present
    login_user: root
    login_password: "{{ suitecrm_db_root_password }}"
  loop:
    - localhost
    - 127.0.0.1
    - ::1
  register: set_root_password
  failed_when: set_root_password.failed

- name: Remove anonymous MySQL users
  community.mysql.mysql_user:
    name: ""
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ suitecrm_db_root_password }}"
  register: remove_anonymous_users
  failed_when: remove_anonymous_users.failed

- name: Disallow root login remotely
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ suitecrm_db_root_password }}"
    state: present
    login_user: root
    login_password: "{{ suitecrm_db_root_password }}"
  loop:
    - 127.0.0.1
    - ::1
  register: disallow_remote_root
  failed_when: disallow_remote_root.failed

- name: Remove MySQL test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ suitecrm_db_root_password }}"
  register: remove_test_db
  failed_when: remove_test_db.failed

- name: Reload privilege tables
  ansible.builtin.command:
    cmd: >
      mysql -u root -p{{ suitecrm_db_root_password }} -e "FLUSH PRIVILEGES;"
  register: reload_privileges
  failed_when: reload_privileges.failed

- name: Create MySQL database
  community.mysql.mysql_db:
    name: "{{ suitecrm_db_name }}"
    state: present
    login_user: root
    login_password: "{{ suitecrm_db_root_password }}"
  register: create_db
  failed_when: create_db.failed

- name: Create MySQL user
  community.mysql.mysql_user:
    name: "{{ suitecrm_db_user }}"
    password: "{{ suitecrm_db_password }}"
    priv: "{{ suitecrm_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ suitecrm_db_root_password }}"
  register: create_user
  failed_when: create_user.failed
