# tasks/clone_repo.yaml

- name: Ensure SSM repo directory exists
  ansible.builtin.file:
    path: "{{ ssm_dockerless_.server.install_dir }}"
    state: directory
    mode: '0755'

- name: Clone or update SSM repository
  ansible.builtin.git:
    repo: "{{ ssm_dockerless_.server.repo_url }}"
    dest: "{{ ssm_dockerless_.server.install_dir }}"
    version: "{{ ssm_dockerless_.server.repo_version | default('master') }}"
    update: true
    force: false # Use `true` with caution, as it can discard local changes
