# tasks/mongodb.yaml

- name: Ensure required repositories are present
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    line: "{{ item }}"
    state: present
  loop:
    - 'http://dl-cdn.alpinelinux.org/alpine/v3.9/main'
    - 'http://dl-cdn.alpinelinux.org/alpine/v3.9/community'
  notify: Update APK cache

- name: Update APK package list
  community.general.apk:
    update_cache: true

- name: Install MongoDB and MongoDB tools
  community.general.apk:
    name:
      - mongodb
      - mongodb-tools
    state: present

- name: Ensure MongoDB is started and enabled
  ansible.builtin.service:
    name: mongodb
    state: started
    enabled: true

- name: Configure MongoDB to listen on the specified port
  ansible.builtin.command: mongo --eval 'db.getSiblingDB("{{ ssm_dockerless_.mongodb.db_name }}").createCollection("dummy")'
  changed_when: false  # Prevents this task from showing as changed if the collection already exists

- name: Set MongoDB environment variables
  ansible.builtin.lineinfile:
    path: /etc/profile.d/mongodb_env.sh
    line: "{{ item }}"
    state: present
  loop:
    - "DB_NAME={{ ssm_dockerless_.mongodb.db_name }}"
    - "DB_PORT={{ ssm_dockerless_.mongodb.db_port }}"
