# tasks/nginx.yaml

- name: Ensure NGINX is installed
  ansible.builtin.apk:
    name: nginx
    state: present

- name: Ensure NGINX config file is removed
  ansible.builtin.file:
    path: "{{ ssm_dockerless_.nginx.config_dir }}"
    state: absent
  changed_when: false  # No change needed if the file is already absent

- name: Copy NGINX custom configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ ssm_dockerless_.nginx.config_dir }}"
    mode: '0644'
  changed_when: true  # This task changes the configuration, so it should always report as changed

- name: Test NGINX configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  ignore_errors: true
  changed_when: false  # Testing config doesn't change the state

- name: Output NGINX test results
  ansible.builtin.debug:
    msg: "NGINX test output: {{ nginx_test.stdout }}"
  when: nginx_test.rc != 0

- name: Ensure NGINX is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  changed_when: false  # This can be true if service is already running and enabled
