# tasks/redis_nginx.yaml

- name: Install Redis
  community.general.apk:
    name: redis
    state: present

- name: Install NGINX
  community.general.apk:
    name: nginx
    state: present

- name: Remove default NGINX configuration
  ansible.builtin.file:
    path: "{{ ssm_dockerless_.nginx.config_dir }}"
    state: absent

- name: Copy custom NGINX configuration from template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ ssm_dockerless_.nginx.config_dir }}"
    mode: '0644'

- name: Ensure NGINX is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
