---
# tasks file for webtrees
- name: Install and Configure Webtrees
  block:
    - name: Install required packages
      ansible.builtin.include_tasks: tasks/install_packages.yml

    - name: Configure Apache
      ansible.builtin.include_tasks: tasks/configure_apache.yml

    - name: Setup Database (MariaDB)
      ansible.builtin.include_tasks: tasks/setup_database.yml

    - name: Configure PHP
      ansible.builtin.include_tasks: tasks/configure_php.yml
