---
# tasks file for webtrees
- name: Install and Configure Webtrees
  block:

    - name: Install required packages
      include_tasks: tasks/install_packages.yml

    - name: Configure Apache
      include_tasks: tasks/configure_apache.yml

    - name: Setup Database (MariaDB)
      include_tasks: tasks/setup_database.yml

    - name: Configure PHP
      include_tasks: tasks/configure_php.yml
