# tasks/setup_database.yml
---
- name: Create MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present

- name: Create MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    host: "{{ mysql_host }}"
    priv: "{{ mysql_database }}.*:ALL"

# You can add more MySQL tasks as needed, such as granting privileges or executing SQL scripts
