---
- name: Ensure application directories are present
  block:
    - name: Ensure docker data directory is present
      ansible.builtin.file:
        path: "{{ docker_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"
    #      when: not docker_dir is exists

    - name: Ensure application directories are present
      block:
        - name: Ensure {{ service_name }}-1 directory is present
          ansible.builtin.file:
            path: "{{ radarr1_dir }}"
            state: directory
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: "0755"
        #          notify: restart Radarr1 containers

        - name: Ensure {{ service_name }}-2 directory is present
          ansible.builtin.file:
            path: "{{ radarr2_dir }}"
            state: directory
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: "0755"
#          notify: restart Radarr2 containers
