- name: Ensure directory exists for {{ service }}
  ansible.builtin.file:
    path: "{{ services[service].dir }}"
    state: directory
    mode: '0755'

- name: Generate compose.yaml for Service {{ service }}
  ansible.builtin.template:
    src: "{{ template_path }}"
    dest: "{{ services[service].dir }}/compose.yaml"
    mode: '0644'

- name: Deploy using docker_compose for {{ service }}
  community.docker.docker_compose_v2:
    project_src: "{{ services[service].dir }}"
    pull: policy
    recreate: auto
