# tasks/create-user_deb-ubu.yml (Debian/Ubuntu)
- name: Install requried packages, if needed
  ansible.builtin.include_tasks: packages_deb-ubu.yml

- name: Create {{ newadmin_username }} user without password
  user:
    name: "{{ newadmin_username }}"
    groups: sudo
    append: true
    state: present
    createhome: true

- name: Password generation
  block:
    - name: Create .passwd directory for {{ newadmin_username }}, if it does not exist
      ansible.builtin.file:
        path: "{{ newadmin_passwd_directory }}"
        state: directory
        mode: '0700'
        owner: "{{ newadmin_username }}"
        group: "{{ newadmin_username }}"

    - name: Generate random password
      set_fact:
        random_password: "{{ lookup('password', '/dev/null length=45 chars=ascii_letters,digits') }}"

    - name: Save the password to a file
      ansible.builtin.blockinfile:
        path: "{{ newadmin_passwd_directory }}/pass.txt"
        block: " {{ random_password }}"
        mode: '0640'
        create: yes
#  when: newadmin_username is changed

- name: Set password for {{ newadmin_username }}
  ansible.builtin.shell: echo "{{ newadmin_username }}:{{ random_password }}" | chpasswd

#- name: Set password for {{ newadmin_username }} using password file
#  ansible.builtin.user:
#    name: "{{ newadmin_username }}"
#    password: "{{ lookup('file', newadmin_password_file) }}"
#  when: newadmin_username is changed
