# tasks/main.yaml
- name: Include OS-specific update tasks/main.yaml
  ansible.builtin.include_tasks:
    update_packages.yaml

- name: Reboot machine if necessary
  ansible.builtin.include_tasks:
    reboot.yaml
  when: reboot_required
