# tasks/reboot.yaml
- name: Check if reboot is required (Ubuntu/Debian only)
  block:
    - name: Check main reboot required flag
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_flag
- name: Reboot the machine
  ansible.builtin.reboot:
    msg: "System reboot due to package updates"
    pre_reboot_delay: 30
    post_reboot_delay: 60
    reboot_timeout: 600
    test_command: uptime
  when: >
    (reboot_check is defined and reboot_check.changed) or
    ansible_facts['os_family'] == 'Alpine'
    ansible_facts['os_family'] == 'Alpine'

- name: Reboot the machine
  ansible.builtin.reboot:
    msg: "System reboot due to package updates"
    pre_reboot_delay: 30
    post_reboot_delay: 60
    reboot_timeout: 600
    test_command: uptime
  when: >
    (reboot_check is defined and reboot_check.changed) or
    ansible_facts['os_family'] == 'Alpine'
