# tasks/main.yml
- name: Update repositories
  ansible.builtin.include_tasks: update-repo.yml

- name: Create new admin user with sudo privileges
  ansible.builtin.include_tasks: create-user.yml

- name: Edit SSH configurations
  block:
    - name: Place SSH key in authorized_keys file
      ansible.builtin.include_tasks: ssh-key.yml

    - name: Edit SSH configuration file
      ansible.legacy.include_tasks: ssh-config.yml

- name: Update repositories
  ansible.builtin.include_tasks: update-repo.yml