# tasks/packages_alpine.yml

- name: Ensure required packages are isntalled on Alpine Linux
  block:
    - name: Install shadow package
      ansible.builtin.apk:
        name: shadow
        state: present
    - name: Install sudo package
      ansible.builtin.apk:
        name: sudo
        state: present