# tasks/packages_deb-ubu.yml

- name: Ensure required packages are isntalled on Debian/Ubuntu
  block:
    - name: Install sudo package
      ansible.builtin.apt:
        name: sudo
        state: present
    - name: Install git package
      ansible.builtin.apt:
        name: git
        state: present
    - name: Install nano package
      ansible.builtin.apt:
        name: nano
        state: present
    - name: Install openssh-server package
      ansible.builtin.apt:
        name: openssh-server
        state: present
    - name: Install curl package
      ansible.builtin.apt:
        name: curl
        state: present
    - name: Install wget package
      ansible.builtin.apt:
        name: wget
        state: present