# tasks/update-repo.yml
- name: Update packages on LXCs and VMs
  block:
    - name: Update apt packages on LXCs (for Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Update apk packages on VMs (for Alpine Linux)
      ansible.builtin.apk:
        update_cache: true
      become: true
      become_user: root
      when: ansible_os_family == 'Alpine'

    - name: Update apt packages on VMs (for Debian-based systems)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
