---
# Install MySQL server
- name: Install MySQL server on Debian/Ubuntu
  ansible.builtin.apt:
    name: mariadb-server
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Install MySQL server on Alpine
  when: ansible_facts['os_family'] == 'Alpine'
  community.general.apk:
    name: mariadb
    state: present

- name: Start and enable MySQL service on Debian/Ubuntu
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Start and enable MySQL service on Alpine
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  when: ansible_facts['os_family'] == 'Alpine'

- name: Set MySQL root password
  failed_when: set_root_password.failed and "password already set" not in set_root_password.msg
  community.mysql.mysql_user:
    name: root
    password: "{{ mysql_db_root_password }}"
    host_all: true
    priv: "*.*:ALL,GRANT"

- name: Create database
  community.mysql.mysql_db:
    name: "{{ mysql_db_name }}"
    state: present

- name: Create database user
  community.mysql.mysql_user:
    name: "{{ mysql_db_user }}"
    password: "{{ mysql_db_password }}"
    priv: "{{ mysql_db_name }}.*:ALL"
    state: present
