---
# Tasks specific to Alpine

# Install common packages
- name: Install common packages on Alpine
  apk:
    name: "{{ setup_machine_packages_common }}"
    state: present

# Install Alpine-specific packages
- name: Install Alpine-specific packages
  apk:
    name: "{{ setup_machine_packages_alpine }}"
    state: present
