---
# Tasks specific to Alpine

# Install common packages
- name: Install common packages on Alpine
  community.general.apk:
    name: "{{ setup_machine_packages_common }}"
    state: present

# Install Alpine-specific packages

- name: Install Alpine-specific packages
  community.general.apk:
    name: "{{ setup_machine_packages_alpine }}"
    state: present
