---
# Tasks specific to Debian

# Install common packages
- name: Install common packages on Debian
  ansible.builtin.apt:
    name: "{{ setup_machine_packages_common }}"
    state: present
    update_cache: true

# Install Debian-specific packages
- name: Install Debian-specific packages
  ansible.builtin.apt:
    name: "{{ setup_machine_packages_debian }}"
    state: present
    update_cache: true
