---
# Tasks specific to Ubuntu

# Install common packages
- name: Install common packages on Ubuntu
  ansible.builtin.apt:
    name: "{{ setup_machine_packages_common }}"
    state: present
    update_cache: true

# Install Ubuntu-specific packages
- name: Install Ubuntu-specific packages
  ansible.builtin.apt:
    name: "{{ setup_machine_packages_debian }}"
    state: present
    update_cache: true
