# meta/main.yaml
galaxy_info:
  author: Masked-Kunsiquat
  description: "Ansible role to update packages and reboot if necessary."
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Alpine
      versions:
        - all
dependencies: []
