---
- name: "TASK 200: NETBOX >> Add temporary interface"
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      device: "{{ inventory_hostname }}"
      name: Temporary_Interface
      form_factor: Virtual
    state: present

- name: "TASK 210: NETBOX >> ADD IP ADDRESS OF ANSIBLE HOST"
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      family: 4
      address: "{{ ansible_host }}/{{ subnet_mask | default(24) }}"
      status: active
      interface:
        name: Temporary_Interface
        device: "{{ inventory_hostname }}"

- name: "TASK 220: NETBOX >> ASSOCIATE IP ADDRESS TO DEVICE"
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ inventory_hostname }}"
      device_type: "{{ hostvars[inventory_hostname]['device_type'] }}"
      platform: "{{ hostvars[inventory_hostname]['platform'] | default('Unknown') }}"
      serial: "{{ ansible_facts['net_serialnum'] | default('N/A') }}"
      status: Active
      primary_ip4: "{{ ansible_host }}/{{ subnet_mask | default(24) }}"
