---
- name: "TASK 10: SETUP SITES"
  netbox.netbox.netbox_site:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data: "{{ item }}"
  loop: "{{ site_list }}"
  loop_control:
    label: "{{ item.name }}"
  no_log: true

- name: "TASK 20: SETUP MANUFACTURERS"
  netbox.netbox.netbox_manufacturer:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ manufacturer }}"
  loop: "{{ manufacturers }}"
  loop_control:
    loop_var: manufacturer
  no_log: true
      
- name: "TASK 30: SETUP DEVICE TYPES"
  netbox.netbox.netbox_device_type:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      model: "{{ device_type.model }}"
      manufacturer: "{{ device_type.manufacturer }}"
      slug: "{{ device_type.slug }}"
      part_number: "{{ device_type.part_number }}"
      is_full_depth: "{{ device.type.full_depth }}"
  loop: "{{ device_types }}"
  loop_control:
    loop_var: device_type
    label: "{{ device_type['model'] }}"
  no_log: true
      
- name: "TASK 40: SETUP PLATFORMS"
  netbox.netbox.netbox_platform:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ platform.name }}"
      slug: "{{ platform.slug }}"
  loop: "{{ platforms }}"
  loop_control:
    loop_var: platform
    label: "{{ platform['name'] }}"
  no_log: true
