---
- name: Setup SuiteCRM
  hosts: ""
  become: true
  roles:
    - suitecrm
  vars:
    suitecrm_web_user: "" # (Set this option if you're using the CLI installer)
    suitecrm_web_user_password: "" # (Set this option if you're using the CLI installer)
    suitecrm_db_name: ""
    suitecrm_db_user: ""
    suitecrm_db_password: ""
    suitecrm_db_root_password: ""
    suitecrm_server_name: ""
    suitecrm_run_cli_installer: "" #  (Set to 'true' if you want to run CLI installer)
    suitcrm_php_version: ""
